#
# Makefile for the fingerprint drivers. added by xiehaifei 150508
#
# Each configuration option enables a list of files.
include $(srctree)/drivers/misc/mediatek/Makefile.custom

ifeq ($(LYCONFIG_COMB_FINGERPRINT_SUPPORT),AFS120)
obj-$(CONFIG_INPUT_AFS120)  += madev.o
endif
